# Generated by Django 2.2.4 on 2019-08-27 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subtracao', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subtracao',
            new_name='Operacao',
        ),
    ]
